version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run: 
          name: Install git
          command: |
            kubectl
      - checkout
      - run:
          name: Install KOTS
          command: curl https://kots.io/install | bash
      - run: kubectl kots version

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
